version: '3.9'
services:
  cloudflare-ddns:
    image: jhenderson00/cloudflare-ddns:v1
    container_name: cloudflare-ddns
    # The following should be commented out, especially on Linux distros using SNAP for docker as it breaks the container
    # security_opt:
    #   - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /Users/joshua/GitHub/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
